import { useState, useEffect, useContext } from "react";
import PhaseBackground from "../layout/PhaseBackground";
import GlassCard from "../layout/GlassCard";
import { EmotionContext } from "../../context/EmotionContext";
import { fetchReflections } from "../../api/dashboard.api";

export default function InsightsPage() {
  const { dashboard } = useContext(EmotionContext);
  const [reflections, setReflections] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadReflections() {
      try {
        const data = await fetchReflections();
        setReflections(data || []);
      } catch (err) {
        console.error("Failed to load reflections:", err);
      } finally {
        setLoading(false);
      }
    }
    loadReflections();
  }, []);

  return (
    <PhaseBackground
      fireflyCount={2}
      showNoise={true}
    >
      <div className="mx-auto flex max-w-6xl flex-col gap-48 px-6 py-64">
        {/* Section Header */}
        <div className="flex flex-col gap-8">
          <span className="text-caption text-white-80">Growth & Patterns</span>
          <h1 className="text-h1 text-white">Emotional Insights</h1>
          <p className="max-w-2xl text-lg text-white-80">
            A structured view of your emotional journey, patterns, and past reflections.
          </p>
        </div>

        {/* AI Weekly Summary Card */}
        <GlassCard variant="elevated" className="flex flex-col gap-24 p-40">
          <div className="flex items-center justify-between">
            <h2 className="text-h2 text-white">Weekly AI Summary</h2>
            <span className="rounded-full border border-white/10 bg-white/5 px-12 py-4 text-xs font-medium text-white-80">
              Generated by Jugnu AI
            </span>
          </div>
          <p className="text-lg leading-relaxed text-white-80">
            {dashboard?.insight?.summary || "Continue logging your mood and reflections to receive detailed AI summaries of your emotional state."}
          </p>
        </GlassCard>

        {/* Trend Breakdown */}
        <div className="grid grid-cols-1 gap-24 md:grid-cols-2">
          <GlassCard className="flex flex-col gap-16 p-32">
            <h3 className="text-xl font-semibold text-white">Mood Distribution</h3>
            <div className="flex flex-col gap-12">
              <p className="text-white-80">Based on your recent check-ins.</p>
              <div className="flex h-12 w-full overflow-hidden rounded-full bg-white/5">
                <div className="h-full w-1/4 bg-[#0F766E]" />
                <div className="h-full w-1/3 bg-[#3B1C6B]" />
                <div className="h-full w-1/6 bg-[#4C1D95]" />
                <div className="h-full w-1/4 bg-[#60A5FA]" />
              </div>
              <div className="flex flex-wrap gap-12 text-xs text-white-80">
                <div className="flex items-center gap-4"><span className="h-8 w-8 rounded-full bg-[#0F766E]" /> Calm</div>
                <div className="flex items-center gap-4"><span className="h-8 w-8 rounded-full bg-[#3B1C6B]" /> Stress</div>
                <div className="flex items-center gap-4"><span className="h-8 w-8 rounded-full bg-[#4C1D95]" /> Anxiety</div>
                <div className="flex items-center gap-4"><span className="h-8 w-8 rounded-full bg-[#60A5FA]" /> Confusion</div>
              </div>
            </div>
          </GlassCard>

          <GlassCard className="flex flex-col gap-16 p-32">
            <h3 className="text-xl font-semibold text-white">Stability Index</h3>
            <div className="flex flex-col gap-8">
              <p className="text-white-80">A measure of emotional consistency.</p>
              <div className="text-4xl font-bold text-white">74%</div>
              <p className="text-sm text-white-80 italic">"Your emotional state has been relatively stable this week."</p>
            </div>
          </GlassCard>
        </div>

        {/* Past Reflections List */}
        <div className="flex flex-col gap-24">
          <h2 className="text-h2 text-white">Recent Reflections</h2>

          {loading ? (
            <div className="space-y-12">
              {[1, 2, 3].map((i) => (
                <div key={i} className="space-y-8 rounded-2xl border border-white/5 bg-white/5 p-24">
                  <div className="h-4 w-24 animate-pulse rounded bg-white/10" />
                  <div className="space-y-4">
                    <div className="h-4 w-full animate-pulse rounded bg-white/10" />
                    <div className="h-4 w-5/6 animate-pulse rounded bg-white/10" />
                  </div>
                </div>
              ))}
            </div>
          ) : reflections.length > 0 ? (
            <div className="grid gap-16">
              {reflections.slice(0, 5).map((r, i) => (
                <GlassCard key={i} variant="subtle" className="flex flex-col gap-8 p-24">
                  <span className="text-xs text-white-80">{new Date(r.createdAt).toLocaleDateString()}</span>
                  <p className="text-body text-white/90">{r.content}</p>
                </GlassCard>
              ))}
            </div>
          ) : (
            <div className="flex flex-col items-center gap-24 rounded-2xl border border-white/5 bg-white/5 p-40 text-center sm:p-64">
              <img
                src={mascot}
                alt="Jugnu mascot"
                className="h-48 w-48 animate-[float_6s_ease-in-out_infinite] opacity-50 sm:h-64 sm:w-64"
              />
              <div className="flex flex-col gap-8">
                <p className="text-lg font-semibold text-white sm:text-xl">No reflections yet.</p>
                <p className="max-w-md text-white-80">
                  Take a moment to write your first reflection. This is where your journey begins.
                </p>
              </div>
            </div>
          )}
        </div>
      </div>
    </PhaseBackground>
  );
}
